### ISSUE TITLE
build_visit fails with Qt on Linux Gentoo

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#183]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
I am having problems getting qt5-everywhere-src-5.10.1 compiled on my Linux Gentoo system. Could some provide some inputs?
Thank you.
--
Valmor

**Comment by biagas** [comment]
Hello Valmor,

Looks like the compiler was complaining about redefinition of 'statx'.
Searching the qt forums, it seems there was a problem with qt and glibc 2.28 that has been fixed in qt newer than the one currently used in visit 3.x versions.  Do you know if your sytem is using glibc 2.28?

Just in case, I'm attaching a modified build_visit script for 3.1.4, utilizing qt 5.14.2 instead of qt 5.10.1.
Could you give this one a try?

Kathleen
[build_visit_3.1.4_qt5142.gz](https://github.com/visit-dav/live-customer-response/files/5576334/build_visit_3.1.4_qt5142.gz)

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

Thanks for the build script. Still no luck; maybe another third party 
package needs to be updated too?

My current version of glibc is 2.32-r2

Log attached.

Thanks,

--

Valmor

**Comment by biagas** [comment]
I saw in the log file that numpy failed to compile. Not sure what the problem is there. Shouldn't have a problem building visit without numpy, it just won't be available.

Qt also appears to have failed to build webengine, even though it indicated it wouldn't be built.
I've attached another build visit file, the only difference betweeen the last one is that it adds '-skip webengine' to the QT configure line.  You can remove the qt-everywhere-srcs-5.14.2 directory and run the new build_visit.

**Comment by biagas** [comment]
forgot the attachment 
[build_visit_314_qt5142.gz](https://github.com/visit-dav/live-customer-response/files/5584996/build_visit_314_qt5142.gz)

**Comment by dealmeidavf** [comment]
Hi,
I went back to this build version since it is the one that gets me closer to an install. The line in the build script that makes the difference is:

`qt_flags="${qt_flags} -skip qtwebengine`

However, this is as far as it gets (please see attached log file below):

>All indications are that VisIt was successfully built.
>Packaging VisIt ... (~10 minutes)
>VisIt package failed.  Giving up
>Unable to build or install VisIt.  Bailing out.
>Error in build process.  See build_visit-3.1.4-qt5142_log for more information. If the error is unclear, please include build_visit->3.1.4-qt5142_log in a  message to the visit-users@ornl.gov list.  You will probably  need to compress the build_visit-3.1.4-qt5142_log using a program like gzip  so it will fit within the size limits for email attachments.

From the foregoing, `VisIt` may be all built and it is just the install that did not work correct?

[build_visit-3.1.4-qt5142_log.gz](https://github.com/visit-dav/live-customer-response/files/5726707/build_visit-3.1.4-qt5142_log.gz)

Thanks for inputs.

--
Valmor

**Comment by biagas** [comment]
From the log files you provided:
```
CMake Error at /usr/local/packages/visit-3.1.4_gcc-9.3.0/visit/build/cmake_install.cmake:1800 (file):
  file INSTALL cannot find
  "/usr/local/packages/visit-3.1.4_gcc-9.3.0/third_party/qt/5.14.2/linux-x86_64_gcc-9.3/plugins/xcbglintegrations".
```
Which is related to visit-dav/live-customer-response#192

Did you ever get the 32bit vs 64bit X11 sorted out?

**Comment by dealmeidavf** [comment]
I think the 32bit for libX11 is gone now. I tried another visit build but no luck. If you could take a look at the attached log file, I would appreciate. It is the same issue though: xcbglintegrations...
Thanks.

[build_visit-3.1.4-qt5142_log.gz](https://github.com/visit-dav/live-customer-response/files/5976795/build_visit-3.1.4-qt5142_log.gz)

**Comment by biagas** [comment]
Qt doesn't seem to be finding all the X11 things it needs (or what seems to be 'normal' for our builds.)

``` 
 X11 specific:
    XLib ................................. no
    XCB Xlib ............................. no
    EGL on X11 ........................... no
```

```
  XCB:
    Using system-provided XCB libraries .. no
    XCB XKB .............................. yes
    XCB XInput ........................... yes
    Native painting (experimental) ....... no
    GL integrations:
      GLX Plugin ......................... no
      EGL-X11 Plugin ..................... no
```
However, VTK's build seems to find the needed X11 just fine.

Another customer had a possibly similar issue, which was resolved by 
creating a symbolic link to /usr/lib64 and put it in the X11R6/lib64 dir and re-running build-visit.
(see https://elist.ornl.gov/mailman/private/visit-developers/2021-January/019379.html)

Barring that, you could modify visit's /src/CMake/FindVisItQt.cmake and comment out (Prefix with a '#') the install commands below: (but I am not sure if VisIt would behave correctly without these qt plugins).
```
     # Xcb related plugins
      install(DIRECTORY ${VISIT_QT_DIR}/plugins/xcbglintegrations
              DESTINATION ${VISIT_INSTALLED_VERSION_LIB}/qtplugins)

          # there is also a platform-plugin related library that
          # needs to be installed, but there doesn't seem to be
          # a way to find this via Qt's cmake mechanisms, hence this
          # hard-coded extra step
          THIRD_PARTY_INSTALL_LIBRARY(${VISIT_QT_DIR}/lib/libQt5XcbQpa.so)
```
You would need to rerun cmake/make/install from the build-dir for visit by hand (I think build_visit would overwrite the changed file).

Given that VisIt built, and only the install failed, have you tried running it from the build-dir. That would give an indication whether or not the Qt build was sufficient for VisIt, and if removing the install commands so that VisIt installs completely without the xcb plugins would even work.
